yolo_model:

  config_file:
    name: yolov3-opl.cfg
  weight_file:
    name: yolov3-opl.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Tomato Soup
      - Green tea
      - Chocolate Snack
      - Detergent
      - Refresher
      - Scrubbing brush
      - Cooling sheet
      - Bond
      - Plaster
      - UNKNOWN1
      - UNKNOWN2
      - UNKNOWN3
